export const METRICS_MAP = [
    {
      name: 'CYCLE TIME',
      label: 'Cycle time',
      value: 'cycle-time',
      valueKey: 'averageTime',
      overviewValueKey:"averageMetricValue",
      valueType: 'time',
      color: '#5059EE',
      toolTip: 'Time from first commit to PR merge.',
      secondaryValueKey: undefined,
      yAxisSuffix: 'time',
      goalKey: 'cycleTime',
      correlatedMetrics: [{
        name: "Coding Time",
        metricKey: "coding-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#67CEDA",
        value: null
      },
      {
        name: "Review Time",
        metricKey: "review-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#77D2A1",
        value: null
      },
      {
        name: "Merge Time",
        metricKey: "merge-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#F3AB42",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: 'cycleTimeAvg',    
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'cycleTimeAvg'
    },
    {
      name: 'DEPLOYMENT FREQUENCY',
      label: 'Deployment Frequency',
      value: 'deployment-frequency',
      valueKey: 'totalCount',
      overviewValueKey: 'totalMetricValue',
      valueType: 'frequency',
      color: '#5059EE',
      toolTip: 'No. of PRs merged to release branches as per configuration.',
      yAxisSuffix: 'frequency',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: 'deploymentFrequency',
      goalKey: 'deploymentFrequency',
      tableHeaderUnit: 'frequencyTotal',
      tableHeaderKey: 'deploymentFrequency'
    },
    {
      name: 'REVIEW TIME',
      label: 'Review time',
      value: 'review-time',
      valueKey: 'averageTime',
      overviewValueKey:"averageMetricValue",
      valueType: 'time',
      color: '#77D2A1',
      toolTip: 'Time from PR Opened to Final Review.',
      yAxisSuffix: 'time',
      goalKey: 'reviewTime',
      correlatedMetrics: [{
        name: "Coding Time",
        metricKey: "coding-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#67CEDA",
        value: null
      },
      {
        name: "Cycle time",
        metricKey: "cycle-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#A5AEC4",
        value: null
      },
      {
        name: "Merge Time",
        metricKey: "merge-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#F3AB42",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: 'reviewTimeAvg',
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'reviewTimeAvg'
    },
    {
      name: 'MERGE TIME',
      label: 'Merge time',
      value: 'merge-time',
      valueKey: 'averageTime',
      overviewValueKey:"averageMetricValue",
      valueType: 'time',
      color: '#F3AB42',
      toolTip: 'Time from Final Review to PR merged.',
      yAxisSuffix: 'time',
      correlatedMetrics: [{
        name: "Coding Time",
        metricKey: "coding-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#67CEDA",
        value: null
      },
      {
        name: "Review Time",
        metricKey: "review-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#77D2A1",
        value: null
      },
      {
        name: "Cycle time",
        metricKey: "cycle-time",
        valueKey: "averageTime",
        valueType: 'time',
        color: "#A5AEC4",
        value: null
      },],
      mediaLink: '',
      tableMetricKey: 'deployTimeAvg',
      goalKey: 'mergeTime',
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'deployTimeAvg'
    },
    {
      name: 'CODING TIME',
      label: 'Coding time',
      value: 'coding-time',
      valueKey: 'averageTime',
      overviewValueKey:"averageMetricValue",
      valueType: 'time',
      color: '#67CEDA',
      toolTip: 'Time from first commit to PR open, excludes draft PRs',
      yAxisSuffix: 'time',
      correlatedMetrics: [
        {
          name: "Review Time",
          metricKey: "review-time",
          valueKey: "averageTime",
          valueType: 'time',
          color: "#77D2A1",
          value: null
        },
        {
          name: "Merge Time",
          metricKey: "merge-time",
          valueKey: "averageTime",
          valueType: 'time',
          color: "#F3AB42",
          value: null
        }, {
          name: "Cycle time",
          metricKey: "cycle-time",
          valueKey: "averageTime",
          valueType: 'time',
          color: "#A5AEC4",
          value: null
        }],
      mediaLink: '',
      tableMetricKey: 'codingTimeAvg',
      goalKey: 'codingTime',
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'codingTimeAvg'
    },
    {
      name: 'FLASHY REVIEWS',
      label: 'Flashy reviews',
      value: 'flashy-reviews',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      secondaryValueKey: 'totalCount',
      valueType: 'percentage',
      color: '#77D2A1',
      // toolTip:
      //   "PRs > 200 LOC modified (added/removed) and reviewed within 5 mins",
      yAxisSuffix: 'count',
      correlatedMetrics: [
        {
          name: "PRs > 400 LOC",
          metricKey: "pr-large",
          valueKey: "precentage",
          valueType: 'percentage',
          color: "#A5AEC4",
          value: null
        },
      ],
      mediaLink: '',
      tableMetricKey: 'flashyReviewPrCount',
      goalKey: 'flashyReviewsCount',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'flashyReviewPrPercentage'
    },
    {
      name: 'CHANGE FAILURE RATE',
      label: 'Change failure rate',
      value: 'change-failure-rate',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      valueType: 'percentage',
      color: '#67CEDA',
      toolTip: 'PRs merged to release branches with the hotfix pattern as configured',
      yAxisSuffix: 'fixes',
      correlatedMetrics: [
        {
          name: "Unreviewed PRs",
          metricKey: "pr-unreviewedmerge",
          valueKey: "totalMetricCount",
          overviewValueKey: "totalMetricValue",
          valueType: 'percentage',
          color: "#5059EE",
          value: null
        },
        {
          name: "PRs reviewed",
          metricKey: "pr-reviewed",
          valueKey: "totalMetricCount",
          overviewValueKey: "totalMetricValue",
          valueType: 'percentage',
          color: "#77D2A1",
          value: null
        },
        {
          name: "Flashy reviews",
          metricKey: "flashy-reviews",
          valueKey: "totalMetricCount",
          valueType: 'percentage',
          color: '#F3AB42',
          value: null
        },
        {
          name: "PRs > 400 LOC",
          metricKey: "pr-large",
          valueKey: "precentage",
          valueType: 'percentage',
          color: "#67CEDA",
          value: null
        },
      ],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'changeFailureRate',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'changeFailureRate'
    },
    {
      name: 'UNREVIEWED PRs',
      label: 'Unreviewed PRs',
      value: 'pr-unreviewedmerge',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      secondaryValueKey: 'metricCount',
      valueType: 'percentage',
      color: '#5059EE',
      toolTip:
        'PRs opened by this author and merged without review in the selected duration.',
      yAxisSuffix: 'count',
      correlatedMetrics: [
        {
          name: "Flashy reviews",
          metricKey: "flashy-reviews",
          valueKey: "totalMetricCount",
          valueType: 'percentage',
          color: "#77D2A1",
          value: null
        }, {
          name: "Change failure rate",
          metricKey: "change-failure-rate",
          valueKey: "totalMetricCount",
          overviewValueKey: "totalMetricValue",
          valueType: 'percentage',
          color: "#A5AEC4",
          value: null
        },
        {
          name: "PRs reviewed",
          metricKey: "pr-reviewed",
          valueKey: "totalMetricCount",
          overviewValueKey: "totalMetricValue",
          valueType: 'percentage',
          color: "#77D2A1",
          value: null
        }, {
          name: "PRs > 400 LOC",
          metricKey: "pr-large",
          valueKey: "precentage",
          valueType: 'percentage',
          color: "#A5AEC4",
          value: null
        },],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'prMergedWithoutReviewPercentage',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'mergedWithoutReviewPrPercentage'
    },
    {
      name: 'PRs REVIEWED',
      label: 'PRs reviewed',
      value: 'pr-reviewed',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      secondaryValueKey: 'totalMetricCount',
      valueType: 'percentage',
      color: '#77D2A1',
      toolTip: 'PRs opened by this author and reviewed by at least one member in the selected duration.',
      yAxisSuffix: 'count',
      correlatedMetrics: [{
        name: "Flashy reviews",
        metricKey: "flashy-reviews",
        valueKey: "totalMetricCount",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }, {
        name: "Change failure rate",
        metricKey: "change-failure-rate",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#A5AEC4",
        value: null
      }, {
        name: "Unreviewed PRs",
        metricKey: "pr-unreviewedmerge",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#5059EE",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'prReviewedCount',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'prsReviewedPercentage'
    },
    {
      name: 'REWORK',
      label: 'Rework',
      value: 'rework',
      valueKey: 'percentage',
      overviewValueKey:"averageMetricValue",
      valueType: 'percentage',
      color: '#F3AB42',
      toolTip: `Code modified that was written within the last \${reworkDuration} days.`,
      yAxisSuffix: 'percentage',
      correlatedMetrics: [{
        name: "Maintenance",
        metricKey: "maintenance",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#5059EE",
        value: null
      }, {
        name: "New work",
        metricKey: "newwork",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'reworkPercentage',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'reWorkPer'
    },
    {
      name: 'MAINTENANCE',
      label: 'Maintenance',
      value: 'maintenance',
      valueKey: 'percentage',
      overviewValueKey:"averageMetricValue",
      valueType: 'percentage',
      color: '#5059EE',
      toolTip: `Code modified that was written prior to \${reworkDuration} days.`,
      yAxisSuffix: 'percentage',
      correlatedMetrics: [{
        name: "Rework",
        metricKey: "rework",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#F3AB42",
        value: null
      }, {
        name: "New work",
        metricKey: "newwork",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'maintenancePercentage',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'maintenanceWorkPer'
    },
    {
      name: 'PRs > 400 LOC',
      label: 'PRs > 400 LOC',
      value: 'pr-large',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      secondaryValueKey: 'totalMetricCount',
      valueType: 'percentage',
      color: '#67CEDA',
      toolTip: 'PRs with more than 400 lines (added + removed)',
      yAxisSuffix: 'count',
      correlatedMetrics: [{
        name: "Flashy reviews",
        metricKey: "flashy-reviews",
        valueKey: "totalMetricCount",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }, {
        name: "Change failure rate",
        metricKey: "change-failure-rate",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#A5AEC4",
        value: null
      }, {
        name: "Unreviewed PRs",
        metricKey: "pr-unreviewedmerge",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#5059EE",
        value: null
      }, {
        name: "PRs reviewed",
        metricKey: "pr-reviewed",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'prGreaterThan400LocCount',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'largeSizePrPercentage'
    },
    {
      name: 'MTTR',
      label: 'MTTR',
      value: 'mttr-duration',
      valueKey: 'totalMetricCount',
      overviewValueKey:"totalMetricValue",
      secondaryValueKey: 'metricCount',
      valueType: 'time',
      color: '#77D2A1',
      toolTip: 'Cycle time of all PRs merged to release branches with the hotfix pattern as configured.',
      yAxisSuffix: 'time',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: null,
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'mttrDurationAvg'
    },
    {
      name: 'COMMITS',
      label: 'Commits',
      value: 'commits',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      valueType: 'count',
      color: '#5059EE',
      toolTip:
        'Number of Code changes made to the repo',
      yAxisSuffix: 'count',
      correlatedMetrics: [{
        name: "PRs Open",
        metricKey: "pr-open",
        valueKey: "totalCount",
        valueType: 'count',
        color: "#77D2A1",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: 'commitCount',
      goalKey: 'commitsCount',
      tableHeaderUnit: 'count',
      tableHeaderKey:'commitCount'
    },
    {
      name: 'PRs OPEN',
      label: "PRs Open",
      value: 'pr-open',
      valueKey: 'totalCount', // TODO: change to totalMetricCount
      overviewValueKey: "totalMetricValue",
      valueType: 'count',
      color: '#67CEDA',
      toolTip: 'Pull Requests opened in the given duration',
      yAxisSuffix: 'count',
      correlatedMetrics: [{
        name: "Commits",
        metricKey: "commits",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'count',
        color: "#5059EE",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'propenCount',
      tableHeaderUnit: 'count',
      tableHeaderKey: 'openPrCount'
    },
    {
      name: 'PRs MERGED',
      label: 'PRs Merged',
      value: 'pr-merged',
      valueKey: 'totalMetricCount',
      overviewValueKey: "totalMetricValue",
      secondaryValueKey: 'metricCount',
      valueType: 'percentage',
      color: '#F3AB42',
      toolTip: 'PRs merged in the selected duration that were opened by this author (not necessarily in the selected duration),  regardless of who merged the PR',
      yAxisSuffix: 'count',
      correlatedMetrics: [{
        name: "Unreviewed PRs",
        metricKey: "pr-unreviewedmerge",
        valueKey: "totalMetricCount",
        valueType: 'percentage',
        color: "#5059EE",
        value: null
      }, {
        name: "PRs reviewed",
        metricKey: "pr-reviewed",
        valueKey: "totalMetricCount",
        overviewValueKey: "totalMetricValue",
        valueType: 'percentage',
        color: "#77D2A1",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'prMergedWithoutReviewCount',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'mergedPrPercentage'
    },
    {
      name: 'NEW WORK',
      label: 'New work',
      value: 'newwork',
      valueKey: 'percentage',
      overviewValueKey:"averageMetricValue",
      valueType: 'percentage',
      color: '#77D2A1',
      toolTip: 'New lines of code added, including to existing files',
      yAxisSuffix: 'percentage',
      correlatedMetrics: [{
        name: "Rework",
        metricKey: "rework",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#F3AB42",
        value: null
      }, {
        name: "Maintenance",
        metricKey: "maintenance",
        valueKey: "percentage",
        overviewValueKey:"averageMetricValue",
        valueType: 'percentage',
        color: "#5059EE",
        value: null
      }],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: 'newWorkPercentage',
      tableHeaderUnit: 'percentAvg',
      tableHeaderKey: 'newWorkPer'
    },
    {
      name: 'Active Days',
      label: "Active days",
      value: 'active-days',
      valueKey: 'totalMetricCount',
      valueType: 'count',
      color: '#A5AEC4',
      toolTip: 'Number of days per week a developer did Git activity',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: 'count',
      tableHeaderKey: 'activeDays'
    },
    {
      name: 'Meetings Breakdown',
      label: "Meetings Breakdown",
      value: 'meetings-breakdown',
      valueKey: 'totalMetricCount',
      valueType: 'time',
      color: '#A5AEC4',
      toolTip: 'Time spent on various meetings',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: null,
      tableHeaderKey: null
    }, {
      name: 'Pipeline metrics',
      label: "Pipeline metrics",
      value: 'pipeline-metric',
      valueKey: 'totalMetricCount',
      valueType: 'time',
      color: '#A5AEC4',
      toolTip: 'Pipeline duration, failure rate',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: null,
      tableHeaderKey: null
    },
    {
      name: 'CLOSED ISSUES COUNT',
      label: 'Closed work items count',
      value: 'closed-issues-count',
      valueKey: 'totalMetricCount',
      valueType: 'count',
      color: '#5059EE',
      toolTip:
        'No. of Work Items closed',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableHeaderUnit: 'count',
      tableHeaderKey: 'closedIssuesCount'
    },
    {
      name: 'COMPLETED STORY POINTS',
      label: 'Completed story points',
      value: 'completed-story-points',
      valueKey: 'totalMetricCount',
      valueType: 'count',
      color: '#5059EE',
      toolTip:
        'No. of Story points completed',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableHeaderUnit: 'count',
      tableHeaderKey: 'completedStoryPoints'
    },
    {
      name: 'Avg PR size',
      label: "Average PR size",
      value: 'average-pr-metric',
      valueKey: 'averagePrSize',
      valueType: 'count',
      color: '#A5AEC4',
      toolTip: 'The average lines changed (added + removed) per merged PR',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: 'avg',
      tableHeaderKey: 'avgPrSize',
      overviewValueKey: 'averageMetricValue'
    },
    {
      name: 'Average Pickup Time',
      label: "Average Pickup Time",
      value: 'pickup-time',
      valueKey: 'averageTime',
      valueType: 'time',
      color: '#A5AEC4',
      toolTip: 'Average time from PR open to first comment (zero if no comment)',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: 'avgTime',
      tableHeaderKey: 'averagePickupTime',
      overviewValueKey: 'averageMetricValue'
    },
    {
      name: 'CODEBASE CHANGES',
      label: 'Codebase Changes',
      value: 'codebase-changes',
      valueKey: 'count',
      overviewValueKey:"averageMetricValue",
      valueType: 'count',
      color: '#77D2A1',
      yAxisSuffix: 'count',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: '',
      goalKey: '',
      tableHeaderUnit: 'count',
      tableHeaderKey: 'codeChanges'
    },
    {
      name: 'MERGE ACTIVITY',
      label: 'Merge activity',
      value: 'merge-activity',
      valueKey: 'totalMetricCount',
      overviewValueKey:"totalMetricValue",
      valueType: 'count',
      color: '#5059EE',
      toolTip: 'PRs merged by team/user in the selected duration',
      secondaryValueKey: undefined,
      yAxisSuffix: 'count',
      goalKey: 'cycleTime',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: 'activelyMergedPrs',    
      tableHeaderUnit: 'count',
      tableHeaderKey: 'activelyMergedPrs'
    },
    {
      name: 'REVIEW ACTIVITY',
      label: 'Review activity',
      value: 'review-activity',
      valueKey: 'totalMetricCount',
      overviewValueKey:"totalMetricValue",
      valueType: 'count',
      color: '#5059EE',
      toolTip: 'The total number of code reviews completed by the user or team during the selected duration, reflecting their review activity',
      secondaryValueKey: undefined,
      yAxisSuffix: 'count',
      goalKey: 'reviewedCount',
      correlatedMetrics: [],
      mediaLink: '',
      tableMetricKey: 'reviewCount',    
      tableHeaderUnit: 'count',
      tableHeaderKey: 'reviewCount'
    },
  ]
  